export default {
    EMAIL: 'EMAIL',
    PASSWORD: 'PASSWORD',
    MATRICULATION_INPUT: 'MATRICULATION_INPUT',
    PHONE: 'PHONE',
    DOB: 'DOB',
    ADDRESS: 'ADDRESS',
    OTP: 'OTP',
    USERNAME: 'USERNAME',
    CONF_PASSWORD: 'CONF_PASSWORD',
    BASE_CHAPTER: 'BASE_CHAPTER',

    TAB_HOME: 'TAB_HOME',
    TAB_CHAT: 'TAB_CHAT',
    TAB_VIDEO_LIB: 'TAB_VIDEO_LIB',
    TAB_GIFT_CARD: 'TAB_GIFT_CARD',
    TAB_ACCOUNT: 'TAB_ACCOUNT',
}