export default {
    EMAIL: 'EMAIL',
    PASSWORD: 'PASSWORD',
    MATRICULATION_INPUT: 'MATRICULATION_INPUT',
    PHONE: 'PHONE',
    DOB: 'DOB',
    ADDRESS: 'ADDRESS',
    OTP: 'OTP',
    USERNAME: 'USERNAME',
    CONF_PASSWORD: 'CONF_PASSWORD'
}