export default {
    ic_logo: require('./ic_logo.png'),
    ic_send: require('./ic_send.png'),
    ic_calendar: require('./ic_calendar.png'),
    bg_soba: require('./bg_soba.png'),
    ic_soba_america: require('./ic_soba_america.png'),
    ic_soba_uk: require('./ic_soba_uk.png'),
    ic_back: require('./ic_back.png'),
    ic_video_library: require('./ic_video_library.svg'),
    ic_home: require('./ic_home.svg'),
    ic_chat: require('./ic_chat.svg'),
    ic_card_giftcard: require('./ic_card_giftcard.svg'),
    ic_account: require('./ic_account.svg'),
    ic_search: require('./ic_search.png'),
    ic_filter: require('./ic_filter.png'),
}